services:
  rabbitmq:
    image: rabbitmq:4.3.4-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_DB: drilling_telemetry
      POSTGRES_USER: drilling_telemetry
      POSTGRES_PASSWORD: ${Postgres__Password}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro

volumes:
  postgres-data:
