@baseUrl = http://localhost:5153

POST {{baseUrl}}/api/simulation/settings
Content-Type: application/json

{
  "deviceIds": [
    "DRILL-101",
    "DRILL-102"
  ],
  "publishingIntervalMilliseconds": 500,
  "drillingOperation": "DrillingAhead",
  "depthChangeRateMetresPerHour": 18
}
